### PR TITLE
Strip R_LDFLAGS strings in FindR.cmake

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Attempting to fix the Windows build.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
So we are now failing at the next step (configure passes, but build does not).

**Comment by JohanMabille** [comment]
It tries to link with the .dll files instead of the companions .lib files.

**Comment by SylvainCorlay** [comment]
Yeah, FindR returns the DLLs.

**Comment by romainfrancois** [comment]
Moving the 🪡 a bit, now with this error : 

```
D:\a\xeus-r\xeus-r\src\xinterpreter.cpp(28): fatal error C1083: Cannot open include file: 'Rinterface.h': No such file or directory
```

**Comment by romainfrancois** [comment]
The `Rinterface.h` file is unix only, we're going to need to set the callbacks differently on windows. See https://vscode.dev/github/rstudio/rstudio/blob/main/src/cpp/r/session/REmbeddedWin32.cpp for how Rstudio does it.

**Pull request closed without merging**
